# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62b4403ade316ac69c72535966af6cd9612f73fd19dd5355a0e0558c340c155e4e4a6e180567bbf18fdec46f13a0a7eff7e08ee85614c33598765840d3764393
  gmail_password: 11Broadway

test:
  secret_key_base: 7f40826b504760cf395e741d68c2e73465a728b5ea3a366187cdf31c922ea5e627bb9720791a5b1744dbe920b81eeb2a53669803b2f6cfcf6dc0ede8f4c0f24e
  gmail_password: 11Broadway

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>